"""empty message

Revision ID: d5df9a06a8fb
Revises: f38da1353e3c
Create Date: 2024-08-07 15:33:02.700444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5df9a06a8fb'
down_revision = 'f38da1353e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional',
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('professional_id')
    )
    op.create_table('thread',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('solve', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('answer',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.thread_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'professional', ['professional'], ['professional_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('professional')

    op.drop_table('answer')
    op.drop_table('thread')
    op.drop_table('professional')
    # ### end Alembic commands ###
